### ISSUE TITLE
error : no such file or directory

### ISSUE THREAD

**Issue by Vinobharathi369** [huihut/OpenCV-MinGW-Build#10]
test.cpp:1:9: fatal error: opencv2/core/core.hpp: No such file or directory
 #include<opencv2/core/core.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

how to compile the opencv with mingw64 build using gcc/g++ compiler?

**Comment by huihut** [comment]
I wrote about how to compile OpenCV with MinGW64 on [this blog](https://blog.huihut.com/2018/07/31/CompiledOpenCVWithMinGW64/). You can use Google Translate to translate into English.
