### ISSUE TITLE
Adding Open 3.4.7 version

### ISSUE THREAD

**Issue by fjafjan** [huihut/OpenCV-MinGW-Build#12]
The latest 3.4 release has some bug fixes in the dnn library that are very useful, would really appreciate if you could build it :)

**Comment by huihut** [comment]
### [OpenCV 3.4.7](https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-3.4.7) | [zip](https://github.com/huihut/OpenCV-MinGW-Build/archive/OpenCV-3.4.7.zip) | [tar.gz](https://github.com/huihut/OpenCV-MinGW-Build/archive/OpenCV-3.4.7.tar.gz)

```
git clone -b OpenCV-3.4.7 git@github.com:huihut/OpenCV-MinGW-Build.git
```

OpenCV 3.4.7 has been added
