### ISSUE TITLE
git clone not working

### ISSUE THREAD

**Issue by yuanyanhui** [huihut/OpenCV-MinGW-Build#16]
git clone -b OpenCV-4.1.1-x64 git@github.com:huihut/OpenCV-MinGW-Build.git
Cloning into 'OpenCV-MinGW-Build'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

The following command worked,
git clone -b OpenCV-4.1.1-x64 --single-branch https://github.com/huihut/OpenCV-MinGW-Build.git

**Comment by huihut** [comment]
Please read <https://github.com/jakubroztocil/cloudtunes/issues/23>

**Comment by huihut** [comment]
@yuanyanhui  Is the problem resolved now?

**Comment by yuanyanhui** [comment]
It's actually not a problem, but beginners like me would prefer the simplicity of http cloning.
