### ISSUE TITLE
how to build opencv2.4.11 mingw windows?

### ISSUE THREAD

**Issue by ioou** [huihut/OpenCV-MinGW-Build#17]

**Comment by huihut** [comment]
* [OpenCV使用CMake和MinGW的编译安装及其在Qt配置运行](https://blog.huihut.com/2017/12/03/CompiledOpenCVRunInQt/)
* [Getting started with OpenCV 2.4 and MinGW on Windows 7](https://stackoverflow.com/a/13038317/7678399)

or you can use Google search.

**Comment by huihut** [comment]
Too long did not reply, so close this issue
