### ISSUE TITLE
作者你好，我在使用你编译出来的库的时候出现了无法定位程序输入点的错误

### ISSUE THREAD

**Issue by clownrat6** [huihut/OpenCV-MinGW-Build#18]
编译环境：
作者提供的编译工具包

这是我的makefile：
```
INCLUDES = -I. -ID:\OpenCV-4.1.1\include
# opencv 主要模块 core,imgproc,highgui,imgcodecs,videoio(注意和video的区别),calib3d,feature2d,video,objdetect,dnn,ml,gapi,cuda
# LIBS = -lopencv_core420 -lopencv_imgcodecs420
LIBDIRS = -L. -LD:\OpenCV-4.1.1\x64\mingw\bin 
LIBS = -lopencv_core411 -lopencv_imgcodecs411
# OPT = -O3 -Wno-deprecated
 
CC=g++

# % 表示匹配当前目录下的所有文件,$@ 代表规则中的目标,$< 指代第一个依赖条件,$^ 指代所有的依赖条件,$+ 与 $^ 相似，只是其不会去除重复的部分。
 
a:*.cpp
	$(CC) $+ $(INCLUDES) $(LIBDIRS) $(LIBS) -o $@ $(OPT)

.PHONY: all clean
clean:
	rm -f *.o 
all:
	echo make complete
```
这是我的main.cpp:
```
#include<opencv2/core.hpp>
#include<opencv2/imgcodecs.hpp>
#include<iostream>

using namespace std;
using namespace cv;

int main()
{
    cv::Mat a;
    a = cv::imread("1.png");
    cout<<a<<endl;
}
```
这是执行输出的a.exe得到的结果：
```
无法定位程序输入点
_ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt1
4default_deleteIS1_EEPFvvE 于动态链接库
D:\OpenCV-4.1.1\x64\mingw\bin\libopencv_imgcodecs411.dll
上。
```

**Comment by liguanjie945** [comment]
你把dll添加到你的执行文件了吗？------------------ 原始邮件 ------------------
发件人: "sennnnn"<notifications@github.com>
发送时间: 2020年1月30日(星期四) 晚上9:37
收件人: "huihut/OpenCV-MinGW-Build"<OpenCV-MinGW-Build@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [huihut/OpenCV-MinGW-Build] 作者你好，我在使用你编译出来的库的时候出现了无法定位程序输入点的错误 (#18)



编译环境：
 作者提供的编译工具包
 
这是我的makefile：
 INCLUDES = -I. -ID:\OpenCV-4.1.1\include # opencv 主要模块 core,imgproc,highgui,imgcodecs,videoio(注意和video的区别),calib3d,feature2d,video,objdetect,dnn,ml,gapi,cuda # LIBS = -lopencv_core420 -lopencv_imgcodecs420 LIBDIRS = -L. -LD:\OpenCV-4.1.1\x64\mingw\bin  LIBS = -lopencv_core411 -lopencv_imgcodecs411 # OPT = -O3 -Wno-deprecated   CC=g++ # % 表示匹配当前目录下的所有文&#x4EF6;,< 指代第一个依赖条&#x4EF6;,+ 与 (CC) (INCLUDES) (LIBS) -o (OPT) .PHONY: all clean clean: 	rm -f *.o  all: 	echo make complete  
这是我的main.cpp:
 #include<opencv2/core.hpp> #include<opencv2/imgcodecs.hpp> #include<iostream> using namespace std; using namespace cv; int main() {     cv::Mat a;     a = cv::imread("1.png");     cout<<a<<endl; }  
这是执行输出的a.exe得到的结果：
 无法定位程序输入点 _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt1 4default_deleteIS1_EEPFvvE 于动态链接库 D:\OpenCV-4.1.1\x64\mingw\bin\libopencv_imgcodecs411.dll 上。  
&mdash;

**Comment by clownrat6** [comment]
dll已经被添加到Path用户变量里面，是不行的，之后把dll就和exe放在同一目录下也不行的，而后我再把dll放在system32下面还是不行的

**Comment by huihut** [comment]
```
无法定位程序输入点...于动态链接库...
```
这个意思是能找到dll文件，但是找不到对应的库入口。原因可能很多，但我猜是你在32位的程序中使用了我编译的64位 [OpenCV-4.1.1-x64](https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.1.1-x64) 导致的，生成64位目标程序就可以了。

**Comment by huihut** [comment]
@sennnnn 现在怎么样了？若是解决了，我将关闭这个 issue。

**Comment by clownrat6** [comment]
感谢作者，暂时先关闭吧，目前已经转为使用 msvc 了，等过一段时间再来转回 MinGW

**Comment by clownrat6** [comment]
这次我大致弄清楚了,

无法定位程序输入点_ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE

这个错误是因为anaconda 中的 LIBSTDC++-6.DLL 与 MinGW64 的LIBSTDC++-6.DLL 冲突所导致的，在配置环境变量时将 MinGW64 的 bin 路径移到高于 anaconda 的 mingw-w64/bin 路径更高优先级的位置就可以了。

**Comment by bbqz007** [comment]
your stdc++ version is too older than what the libopencv is compiled with.

the opencv3.4 is compiled with gcc7, and the document of the repo says gcc8, i think the opencv4 maybe compiled with gcc8.

make sure you link a newer stdc++.dll during runtime.

**Comment by ZJUGuoShuai** [comment]
> 这次我大致弄清楚了,
> 
> 无法定位程序输入点_ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE
> 
> 这个错误是因为anaconda 中的 LIBSTDC++-6.DLL 与 MinGW64 的LIBSTDC++-6.DLL 冲突所导致的，在配置环境变量时将 MinGW64 的 bin 路径移到高于 anaconda 的 mingw-w64/bin 路径更高优先级的位置就可以了。

牛，这个问题真的把我搞死，果然是 Conda 搞的鬼。

**Comment by ycdhqzhiai** [comment]
@sennnnn 我也遇见了这个问题，但是我没有安装ancoda，
![image](https://github.com/huihut/OpenCV-MinGW-Build/assets/12273405/ddf3f34f-3175-4ce3-aed4-072b2cee2d64)
我这种的话该怎么处理啊

**Comment by WRtux** [comment]
@sennnnn @ycdhqzhiai  
Found that one import `_ZNSi5seekgESt4fposIiE` from `libstdc++-6.dll` has changed in newer versions of GCC.
For my current setup (MinGW-w64 12.2.0), the signature now becomes `_ZNSi5seekgESt4fposI9_MbstatetE`.
More mismatches may exist as well.

To solve this problem, use a `libstdc++-6.dll` from older versions of MinGW.

---

@huihut  
I suggest adding `-static-libstdc++` when building to eliminate the dependency on specific versions of MinGW.

**Comment by Feanus** [comment]
神仙谢谢

**Comment by mea459** [comment]
谢谢大佬
