### ISSUE TITLE
编译通过但是打不开，缺少dll

### ISSUE THREAD

**Issue by wjdready** [huihut/OpenCV-MinGW-Build#19]
![image](https://user-images.githubusercontent.com/56392070/75219129-eaac4e00-57d6-11ea-8c93-f0195da57f60.png)

还说缺少 QtCore.dll ，为什么要用到 Qt 库才能运行？

**Comment by huihut** [comment]
使用的是哪个版本的 [releases](https://github.com/huihut/OpenCV-MinGW-Build#releases) ？

**Comment by wjdready** [comment]
基本每个版本都有这个问题,你是用Qt 来编译的吗

**Comment by huihut** [comment]
一般x64的没有链接Qt库，x86的链接了，具体看各个release的Configuration，如果都不合你的需求只能自己编译了。

```makefile
  GUI: 
    QT:                          YES (ver 5.13.0)
      QT OpenGL support:         YES (Qt5::OpenGL 5.13.0)
```

**Comment by bbqz007** [comment]
if you see the warning with `libgcc_s_seh-1.dll`,  you are using x64 releases.

other with `libgcc_s_dw2-1.dll`, you are using x86 32bit releases.
