### ISSUE TITLE
Opencv nonfree build 

### ISSUE THREAD

**Issue by darkworks** [huihut/OpenCV-MinGW-Build#20]
Hi hope you doing well

i wonder can you please build opencv 4 x86  with flag = OPENCV_ENABLE_NONFREE   

also can you upload your app : https://github.com/avamoe/Avalive  to gog.com i tried to buy it on steam but steam have strange country lock issue will not let me buy because of different steam account country and paypal . so will be thankful if u can upload to gog.com i would love to buy it

thanks

**Comment by huihut** [comment]
Sorry, this repository only compiles the default configuration, otherwise there are too many different configurations to compile.

Avalive does not plan to upload to gog.com. And I am too busy, Avalive is not maintained much.😓

**Comment by huihut** [comment]
@darkworks  The latest [OpenCV-4.5.0-with-contrib](https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.5.0-with-contrib) has been built, 32-bit, OPENCV_ENABLE_NONFREE =ON, contains the opencv_contrib module.
