### ISSUE TITLE
OpenCV4.4

### ISSUE THREAD

**Issue by 2694048168** [huihut/OpenCV-MinGW-Build#22]
Hi, huihut. 
Can you provide the compilation of OpenCV4.4? 
If you can add the opencv_contrib4.4 extension library module to compile, it would be even better. 
Looking forward to OpenCV4.4！

**Comment by MrPeterJin** [comment]
Hi,
Same as this post, I have complied OpenCV 4.4.0 but failed with an unknown issue. Can you provide a 4.4.0 version?

> Hi, huihut.
> Can you provide the compilation of OpenCV4.4?
> If you can add the opencv_contrib4.4 extension library module to compile, it would be even better.
> Looking forward to OpenCV4.4！

**Comment by huihut** [comment]
@2694048168 @MrPeterJin  The latest [OpenCV-4.5.0-with-contrib](https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.5.0-with-contrib) has been built, 32-bit, contains the opencv_contrib module.

**Comment by 2694048168** [comment]
> @2694048168 @MrPeterJin The latest [OpenCV-4.5.0-with-contrib](https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.5.0-with-contrib) has been built, 32-bit, contains the opencv_contrib module.

Thanks, huihut !

**Comment by mauler2025** [comment]
@huihut Could you provide us with the 64bit version with mingw-64 version 8 as soon as you can?

**Comment by huihut** [comment]
> @huihut Could you provide us with the 64bit version with mingw-64 version 8 as soon as you can?

@pstricks-fans Did you mean https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.1.1-x64

**Comment by mauler2025** [comment]
@huihut : I need the newest OpenCV 4.5.1. By the way, could you review my issue [here](https://github.com/opencv/opencv/issues/19843)?

**Comment by mauler2025** [comment]
@huihut : You did not provide the 64 bit version for https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.5.0-with-contrib. Is it due to the same issue in https://github.com/opencv/opencv/issues/19843 ?

**Comment by huihut** [comment]
@pstricks-fans The latest opencv [OpenCV-4.5.2-x64](https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.5.2-x64)

**Comment by mauler2025** [comment]
@huihut Thank you very much!!!!!!!!
