### ISSUE TITLE
4.11能用但4.50不能用

### ISSUE THREAD

**Issue by Lophyads** [huihut/OpenCV-MinGW-Build#24]
请问是因为编译器不同的选择吗，我用的是mingw 64

**Comment by huihut** [comment]
应该是的。带有x64的是mingw-w64编译的64位的库，用于链接64位的程序；没有x64的是32位的库，用于链接32位的程序。

**Comment by Lophyads** [comment]
那有什么解决办法吗，我自己编译会显示SSL connect error,科学上网也不行
