### ISSUE TITLE
opencv4 alpha

### ISSUE THREAD

**Issue by reg31** [huihut/OpenCV-MinGW-Build#3]
Hi,

Is is possible to have a 64bits version of opencv4?

Thanks

**Comment by huihut** [comment]
@reg31 I tried to compile opencv-4.0.0-alpha using mingw-w64, but there was a problem. <https://github.com/opencv/opencv/issues/12642>

**Comment by huihut** [comment]
@reg31 OpenCV-4.0.0-alpha-x64 has been compiled successfully and uploaded to [OpenCV-4.0.0-alpha-x64](https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.0.0-alpha-x64)
