### ISSUE TITLE
Linking failure with Qt 5.12

### ISSUE THREAD

**Issue by reg31** [huihut/OpenCV-MinGW-Build#4]
Getting undefined references since Qt now uses MinGW 7.3.0

undefined reference to `cv::CascadeClassifier::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

**Comment by huihut** [comment]
oh, I didn't compile QT to OpenCV, Because I don't have 64bit qmake.

**Comment by reg31** [comment]
I guess if you use MinGW 7.3.0 instead of 4.8.1 it would work anyway.

**Comment by reg31** [comment]
Opencv 4 beta, is out.

**Comment by reg31** [comment]
Opencv 4 rc is out.

**Comment by huihut** [comment]
😂😂😂

**Comment by huihut** [comment]
@reg31  [OpenCV-4.0.0-rc-x64](https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.0.0-rc-x64)

**Comment by reg31** [comment]
Good job, well done :)
