### ISSUE TITLE
楼主您好，我想问一下4.0.1版的lib文件为什么都是400结尾的

### ISSUE THREAD

**Issue by zhoujinzhoujin** [huihut/OpenCV-MinGW-Build#7]
例如3.4.5版是以345结尾的，4.0.1不应该是401吗……

**Comment by huihut** [comment]
那确实是官网4.0.1源码编译的，我也觉得奇怪嘞

**Comment by huihut** [comment]
抱歉，似乎是我编译错了，那个好像是4.0.0的源码编译的，晚点我再编译一个4.0.1的

**Comment by huihut** [comment]
Recommit 4.0.1 x64

### [OpenCV 4.0.1-x64](https://github.com/huihut/OpenCV-MinGW-Build/tree/OpenCV-4.0.1-x64) | [zip](https://github.com/huihut/OpenCV-MinGW-Build/archive/OpenCV-4.0.1-x64.zip) | [tar.gz](https://github.com/huihut/OpenCV-MinGW-Build/archive/OpenCV-4.0.1-x64.tar.gz)

```
git clone -b OpenCV-4.0.1-x64 git@github.com:huihut/OpenCV-MinGW-Build.git
```
