### ISSUE TITLE
wenrjianr diusir

### ISSUE THREAD

**Issue by runsys** [huihut/OpenCV-MinGW-Build#8]
m:/work/tool/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_face410
m:/work/tool/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_xfeatures2d410
m:/work/tool/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_plot410
m:/work/tool/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_tracking410
m:/work/tool/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_img_hash410

**Comment by huihut** [comment]
The linker could not find opencv library (libopencv\_\*.dll for VC, libopencv_*.dll.a for GCC)

* You should declare the library path
```
g++ -L/path/to/OpenCV-MinGW-Build/x64/mingw/lib -lopencv_face -lopencv_xfeatures2d -lopencv_plot -lopencv_tracking -lopencv_img_hash yourprogram.cpp -o  yourprogram
```
* Or you can set the library path(`/path/to/OpenCV-MinGW-Build/x64/mingw/lib`) to the environment variable and take effect, then
```
g++ -lopencv_face -lopencv_xfeatures2d -lopencv_plot -lopencv_tracking -lopencv_img_hash yourprogram.cpp -o  yourprogram
```

**Comment by Vinobharathi369** [comment]
> 
> 
> The linker could not find opencv library (libopencv_*.dll for VC, libopencv_*.dll.a for GCC)
> 
>     * You should declare the library path
> 
> 
> ```
> g++ -L/path/to/OpenCV-MinGW-Build/x64/mingw/lib -lopencv_face -lopencv_xfeatures2d -lopencv_plot -lopencv_tracking -lopencv_img_hash yourprogram.cpp -o  yourprogram
> ```
> 
>     * Or you can set the library path(`/path/to/OpenCV-MinGW-Build/x64/mingw/lib`) to the environment variable and take effect, then
> 
> 
> ```
> g++ -lopencv_face -lopencv_xfeatures2d -lopencv_plot -lopencv_tracking -lopencv_img_hash yourprogram.cpp -o  yourprogram
> ```

I tried but not working

**Comment by huihut** [comment]
Maybe you can try @anysz ‘s [solution](https://github.com/huihut/OpenCV-MinGW-Build/issues/9#issuecomment-494809799), and extend opencv_contrib.
