### ISSUE TITLE
Missing Library MinGW build x64

### ISSUE THREAD

**Issue by ii64** [huihut/OpenCV-MinGW-Build#9]
Hello, It's nice to see you created build result of opencv 4.0.1 for MinGW, however i got error lib not exist like picture shown below, but it solved so i just put this issue here and close it (in case someone got same error like mine)
![image](https://user-images.githubusercontent.com/26342994/58100379-b7191380-7c07-11e9-99f8-e841b3764b52.png)

```
D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_face401
D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_xfeatures2d401
D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_plot401
D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_tracking401
D:/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_img_hash401
collect2.exe: error: ld returned 1 exit status
````

so i tried to build them from source, then i found some libs is not exist in your build
i hope you update the build result, thank you

**Comment by huihut** [comment]
@anysz Is your errors similar to [issue#8](https://github.com/huihut/OpenCV-MinGW-Build/issues/8)?

Can you solve it according to my [comments](https://github.com/huihut/OpenCV-MinGW-Build/issues/8#issuecomment-492089226)? How did you solve it?

**Comment by ii64** [comment]
> @anysz Is your errors similar to issue#8?

Yes

> How did you solve it?

I build them from source, then i found some libs is not exist in your build, so i copied all my build and replace yours
```batch
cmake D:\LINE\_prj_shared\ImageSimmilar\opencv-4.0.1 -G "MinGW Makefiles" -BD:\LINE\_prj_shared\ImageSimmilar\build -DENABLE_CXX11=ON -DOPENCV_EXTRA_MODULES_PATH=D:\LINE\_prj_shared\ImageSimmilar\opencv_contrib-4.0.1\modules -DBUILD_SHARED_LIBS=ON -DWITH_IPP=OFF -DWITH_MSMF=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_DOCS=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_saliency=OFF -DCPU_DISPATCH= -DOPENCV_GENERATE_PKGCONFIG=ON -Wno-dev
cd /d D:\LINE\_prj_shared\ImageSimmilar\build
mingw32-make -j%NUMBER_OF_PROCESSORS%
mingw32-make install

cd /d D:\LINE\_prj_shared\ImageSimmilar
```

Somehow i got this error build for C++ using g++ compiler
![image](https://user-images.githubusercontent.com/26342994/58179083-a339e400-7cd1-11e9-9914-eaa4a880b919.png)

Did you know why? because golang is working just fine (although i got [this error](https://github.com/hybridgroup/gocv/issues/451))
Thanks for replying anw

**Comment by huihut** [comment]
Thank you for providing your solution. 
What you are experiencing may be an ld link error, but I don't know what caused it.
